name: Mondraq-Gardener
version: 1.0
main: com.mondraq.main.Main
api-version: 1.21
soft-depend: [Vault]
depend: [Citizens]
description: Gardener plugin by Mondraq

commands:
  gardener:
    description: Main gardener command
    usage: /gardener <setarea|npc|reload>
    permission: gardener.admin
